version: '3.8'

services:
  angular-app:
    image: node:18.18.1
    container_name: angular-app
    working_dir: /app
    command: ["bash", "-c", "npm install && npm start"]
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - node-server

  node-server:
    image: node:18.18.1
    container_name: nodejs-app
    working_dir: /app
    command: ["bash", "-c", "npm install && npm start"]
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - port=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
